name: google_ml_kit_example
description: Demonstrates how to use the google_ml_kit plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path: ^1.9.0
  path_provider: ^2.1.3
  google_mlkit_face_detection: ^0.11.0
  sqflite: ^2.0.2
  get_it: ^7.2.0
  image: ^3.0.2
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/mobile_face_net.tflite
